### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by keballantyne** [eodms-sgdot/py-eodms-rapi#34]
The following error occurs when query NAPL images:

```ERROR:
Traceback (most recent call last):
  File "eodms_cli.py", line 1680, in cli
    prmpt.prompt()
  File "eodms_cli.py", line 1214, in prompt
    self.eod.search_order_download(self.params)
  File "C:\GRA\RaD\10-satellitePython\eodms-cli\scripts\utils.py", line 1601, in search_order_download
    max_images=max_images)
  File "C:\GRA\RaD\10-satellitePython\eodms-cli\scripts\utils.py", line 1309, in query_entries
    result_fields, max_images)
  File "C:\Users\frase\miniconda3\envs\satellite_env\lib\site-packages\eodms_rapi\eodms.py", line 3091, in search
    params['query'] = self._parse_query(filters, features, dates)
  File "C:\Users\frase\miniconda3\envs\satellite_env\lib\site-packages\eodms_rapi\eodms.py", line 1233, in _parse_query
    if val[0].lower().find('t') > -1 \
AttributeError: 'bool' object has no attribute 'lower'
```

**Comment by keballantyne** [comment]
Fixed in release https://github.com/eodms-sgdot/py-eodms-rapi/commit/175a11239af061c7b83e00a20a497eb39ebe6955
